-- CASO 1
-- EJECUTAR COMO ADMIN

DEFINE DEFAULT_TS = USERS;
DEFINE TEMP_TS    = TEMP;

-- FUNCION DE VERIFICACION
CREATE OR REPLACE FUNCTION ADMIN.PRY2205_VERIFY_PASSWORD (
    p_username     VARCHAR2,
    p_password     VARCHAR2,
    p_old_password VARCHAR2
) RETURN BOOLEAN IS
BEGIN
    IF p_password IS NULL OR LENGTH(p_password) < 12 THEN
        raise_application_error(-20001, 'Password: mínimo 12 caracteres.');
    END IF;

    IF REGEXP_COUNT(p_password, '[a-z]') < 1 THEN
        raise_application_error(-20002, 'Password: mínimo 1 minúscula.');
    END IF;

    IF REGEXP_COUNT(p_password, '[A-Z]') < 2 THEN
        raise_application_error(-20003, 'Password: mínimo 2 mayúsculas.');
    END IF;

    IF REGEXP_COUNT(p_password, '[0-9]') < 2 THEN
        raise_application_error(-20004, 'Password: mínimo 2 números.');
    END IF;

    IF INSTR(UPPER(p_password), UPPER(p_username)) > 0 THEN
        raise_application_error(-20005, 'Password: no puede contener el nombre del usuario.');
    END IF;

    RETURN TRUE;
END;
/
SHOW ERRORS;

-- PERFIL
BEGIN
  EXECUTE IMMEDIATE 'DROP PROFILE PRY2205_PROFILE_STRONG CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE PROFILE PRY2205_PROFILE_STRONG LIMIT
  PASSWORD_VERIFY_FUNCTION ADMIN.PRY2205_VERIFY_PASSWORD;

-- LIMPIEZA DE USUARIOS
BEGIN EXECUTE IMMEDIATE 'DROP USER PRY2205_EFT CASCADE';      EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP USER PRY2205_EFT_DES CASCADE';  EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP USER PRY2205_EFT_CON CASCADE';  EXCEPTION WHEN OTHERS THEN NULL; END; /

-- CREACION DE USUARIOS
CREATE USER PRY2205_EFT
IDENTIFIED BY "User1AA11pass"
DEFAULT TABLESPACE &&DEFAULT_TS
TEMPORARY TABLESPACE &&TEMP_TS
QUOTA 10M ON &&DEFAULT_TS
PROFILE PRY2205_PROFILE_STRONG;

CREATE USER PRY2205_EFT_DES
IDENTIFIED BY "User2BB22pass"
DEFAULT TABLESPACE &&DEFAULT_TS
TEMPORARY TABLESPACE &&TEMP_TS
QUOTA 10M ON &&DEFAULT_TS
PROFILE PRY2205_PROFILE_STRONG;

CREATE USER PRY2205_EFT_CON
IDENTIFIED BY "User3CC33pass"
DEFAULT TABLESPACE &&DEFAULT_TS
TEMPORARY TABLESPACE &&TEMP_TS
QUOTA 10M ON &&DEFAULT_TS
PROFILE PRY2205_PROFILE_STRONG;

-- ROLES PARA USUARIOS
BEGIN EXECUTE IMMEDIATE 'DROP ROLE PRY2205_ROL_D'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE PRY2205_ROL_C'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/

CREATE ROLE PRY2205_ROL_D;
CREATE ROLE PRY2205_ROL_C;

-- PRIVILEGIOS DE LOS USUARIOS
-- Owner PRY2205_EFT
GRANT CREATE SESSION TO PRY2205_EFT;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO PRY2205_EFT;
GRANT CREATE SYNONYM, CREATE PUBLIC SYNONYM, DROP PUBLIC SYNONYM TO PRY2205_EFT;

-- Dev PRY2205_EFT_DES 
GRANT CREATE SESSION TO PRY2205_EFT_DES;
GRANT CREATE VIEW TO PRY2205_EFT_DES;
GRANT CREATE USER, ALTER USER, DROP USER TO PRY2205_EFT_DES;
GRANT CREATE PROFILE, ALTER PROFILE, DROP PROFILE TO PRY2205_EFT_DES;

-- Con PRY2205_EFT_CON 
GRANT CREATE SESSION TO PRY2205_EFT_CON;

-- ASIGNACION DE ROLES A USUARIOS
GRANT PRY2205_ROL_D TO PRY2205_EFT_DES;
GRANT PRY2205_ROL_C TO PRY2205_EFT_CON;

COMMIT;

-- EJECUTAR COMO OWNER (PRY2205_EFT)
-- CREACION DE TABLAS Y POBLADO EJECUTADO EN ESTE PUNTO

-- VISTAS   
CREATE OR REPLACE VIEW VW_AFP            AS SELECT * FROM AFP;
CREATE OR REPLACE VIEW VW_ISAPRE         AS SELECT * FROM ISAPRE;
CREATE OR REPLACE VIEW VW_PROFESION      AS SELECT * FROM PROFESION;
CREATE OR REPLACE VIEW VW_COMUNA         AS SELECT * FROM COMUNA;
CREATE OR REPLACE VIEW VW_SECTOR         AS SELECT * FROM SECTOR;
CREATE OR REPLACE VIEW VW_TIPO_CONTRATO  AS SELECT * FROM TIPO_CONTRATO;
CREATE OR REPLACE VIEW VW_RANGOS_SUELDOS AS SELECT * FROM RANGOS_SUELDOS;
CREATE OR REPLACE VIEW VW_PROFESIONAL    AS SELECT * FROM PROFESIONAL;
CREATE OR REPLACE VIEW VW_EMPRESA        AS SELECT * FROM EMPRESA;
CREATE OR REPLACE VIEW VW_ASESORIA       AS SELECT * FROM ASESORIA;
CREATE OR REPLACE VIEW VW_CARTOLA_PROF   AS SELECT * FROM CARTOLA_PROFESIONALES;

-- SINONIMOS PUBLICOS CON NOMBRES ALTERNATIVOS
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM S_AFP';            EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM S_ISAPRE';         EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM S_PROFESION';      EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM S_COMUNA';         EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM S_SECTOR';         EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM S_TIPO_CONTRATO';  EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM S_RANGOS_SUELDOS'; EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM S_PROFESIONAL';    EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM S_EMPRESA';        EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM S_ASESORIA';       EXCEPTION WHEN OTHERS THEN NULL; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM S_CARTOLA_PROF';   EXCEPTION WHEN OTHERS THEN NULL; END; 
/


CREATE PUBLIC SYNONYM S_AFP            FOR PRY2205_EFT.VW_AFP;
CREATE PUBLIC SYNONYM S_ISAPRE         FOR PRY2205_EFT.VW_ISAPRE;
CREATE PUBLIC SYNONYM S_PROFESION      FOR PRY2205_EFT.VW_PROFESION;
CREATE PUBLIC SYNONYM S_COMUNA         FOR PRY2205_EFT.VW_COMUNA;
CREATE PUBLIC SYNONYM S_SECTOR         FOR PRY2205_EFT.VW_SECTOR;
CREATE PUBLIC SYNONYM S_TIPO_CONTRATO  FOR PRY2205_EFT.VW_TIPO_CONTRATO;
CREATE PUBLIC SYNONYM S_RANGOS_SUELDOS FOR PRY2205_EFT.VW_RANGOS_SUELDOS;
CREATE PUBLIC SYNONYM S_PROFESIONAL    FOR PRY2205_EFT.VW_PROFESIONAL;
CREATE PUBLIC SYNONYM S_EMPRESA        FOR PRY2205_EFT.VW_EMPRESA;
CREATE PUBLIC SYNONYM S_ASESORIA       FOR PRY2205_EFT.VW_ASESORIA;
CREATE PUBLIC SYNONYM S_CARTOLA_PROF   FOR PRY2205_EFT.VW_CARTOLA_PROF;

-- PRIVILEGIOS ESPECIFICOS A ROLES
GRANT SELECT ON VW_AFP            TO PRY2205_ROL_D;
GRANT SELECT ON VW_ISAPRE         TO PRY2205_ROL_D;
GRANT SELECT ON VW_PROFESION      TO PRY2205_ROL_D;
GRANT SELECT ON VW_COMUNA         TO PRY2205_ROL_D;
GRANT SELECT ON VW_SECTOR         TO PRY2205_ROL_D;
GRANT SELECT ON VW_TIPO_CONTRATO  TO PRY2205_ROL_D;
GRANT SELECT ON VW_RANGOS_SUELDOS TO PRY2205_ROL_D;
GRANT SELECT ON VW_PROFESIONAL    TO PRY2205_ROL_D;
GRANT SELECT ON VW_EMPRESA        TO PRY2205_ROL_D;
GRANT SELECT ON VW_ASESORIA       TO PRY2205_ROL_D;
GRANT SELECT ON VW_CARTOLA_PROF   TO PRY2205_ROL_D;

GRANT SELECT ON VW_AFP            TO PRY2205_ROL_C;
GRANT SELECT ON VW_ISAPRE         TO PRY2205_ROL_C;
GRANT SELECT ON VW_PROFESION      TO PRY2205_ROL_C;
GRANT SELECT ON VW_COMUNA         TO PRY2205_ROL_C;
GRANT SELECT ON VW_SECTOR         TO PRY2205_ROL_C;
GRANT SELECT ON VW_TIPO_CONTRATO  TO PRY2205_ROL_C;
GRANT SELECT ON VW_RANGOS_SUELDOS TO PRY2205_ROL_C;
GRANT SELECT ON VW_PROFESIONAL    TO PRY2205_ROL_C;
GRANT SELECT ON VW_EMPRESA        TO PRY2205_ROL_C;
GRANT SELECT ON VW_ASESORIA       TO PRY2205_ROL_C;
GRANT SELECT ON VW_CARTOLA_PROF   TO PRY2205_ROL_C;

COMMIT;

-- CASO 2
-- COMO PRY2205_EFT (OWNER)

GRANT INSERT, DELETE ON CARTOLA_PROFESIONALES TO PRY2205_EFT_DES;
GRANT SELECT ON CARTOLA_PROFESIONALES TO PRY2205_EFT_DES WITH GRANT OPTION;

-- COMO PRY2205_EFT_DES

GRANT SELECT ON PRY2205_EFT.CARTOLA_PROFESIONALES TO PRY2205_EFT_CON;

-- VACIAR ANTES
DELETE FROM PRY2205_EFT.CARTOLA_PROFESIONALES;

-- INSERCION A LA CARTOLA
INSERT INTO PRY2205_EFT.CARTOLA_PROFESIONALES
(
  RUT_PROFESIONAL,
  NOMBRE_PROFESIONAL,
  PROFESION,
  ISAPRE,
  SUELDO_BASE,
  PORC_COMISION_PROFESIONAL,
  VALOR_TOTAL_COMISION,
  PORCENTATE_HONORARIO,
  BONO_MOVILIZACION,
  TOTAL_PAGAR
)
SELECT
  p.RUTPROF AS rut_profesional,

  (p.NOMPRO || ' ' || p.APPPRO || ' ' || p.APMPRO) AS nombre_profesional,

  pr.NOMPROFESION AS profesion,
  i.NOMISAPRE     AS isapre,

  ROUND(p.SUELDO,0) AS sueldo_base,

  NVL(p.COMISION,0) AS porc_comision_profesional,

  ROUND(ROUND(p.SUELDO,0) * NVL(p.COMISION,0), 0) AS valor_total_comision,

  CASE
    WHEN tc.NOMTCONTRATO = 'Honorarios'
      THEN ROUND(ROUND(p.SUELDO,0) * (NVL(rs.HONOR_PCT,0) / 100), 0)
    ELSE 0
  END AS porcentate_honorario,

  CASE tc.NOMTCONTRATO
    WHEN 'Indefinido Jornada Completa' THEN 150000
    WHEN 'Indefinido Jornada Parcial'  THEN 120000
    WHEN 'Plazo fijo'                  THEN 60000
    WHEN 'Honorarios'                  THEN 50000
    ELSE 0
  END AS bono_movilizacion,

  ROUND(p.SUELDO,0)
  + ROUND(ROUND(p.SUELDO,0) * NVL(p.COMISION,0), 0)
  + CASE
      WHEN tc.NOMTCONTRATO = 'Honorarios'
        THEN ROUND(ROUND(p.SUELDO,0) * (NVL(rs.HONOR_PCT,0) / 100), 0)
      ELSE 0
    END
  + CASE tc.NOMTCONTRATO
      WHEN 'Indefinido Jornada Completa' THEN 150000
      WHEN 'Indefinido Jornada Parcial'  THEN 120000
      WHEN 'Plazo fijo'                  THEN 60000
      WHEN 'Honorarios'                  THEN 50000
      ELSE 0
    END AS total_pagar
FROM S_PROFESIONAL p
JOIN S_PROFESION pr
  ON pr.IDPROFESION = p.IDPROFESION
JOIN S_ISAPRE i
  ON i.IDISAPRE = p.IDISAPRE
LEFT JOIN S_TIPO_CONTRATO tc
  ON tc.IDTCONTRATO = p.IDTCONTRATO
LEFT JOIN S_RANGOS_SUELDOS rs
  ON ROUND(p.SUELDO,0) BETWEEN rs.S_MIN AND rs.S_MAX;

COMMIT;

-- INFORME
SELECT
  RUT_PROFESIONAL,
  NOMBRE_PROFESIONAL,
  PROFESION,
  ISAPRE,
  SUELDO_BASE,
  PORC_COMISION_PROFESIONAL,
  VALOR_TOTAL_COMISION,
  PORCENTATE_HONORARIO,
  BONO_MOVILIZACION,
  TOTAL_PAGAR
FROM PRY2205_EFT.CARTOLA_PROFESIONALES
ORDER BY
  PROFESION ASC,
  SUELDO_BASE DESC,
  PORC_COMISION_PROFESIONAL ASC,
  RUT_PROFESIONAL ASC;

-- CASO 3
-- CASO 3.1
-- EJECUTAR COMO PRY2205_EFT (OWNER)

-- EN CASO DE EXISTIR, BORRAR
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW VW_EMPRESAS_ASESORADAS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
 
CREATE OR REPLACE VIEW VW_EMPRESAS_ASESORADAS AS
SELECT
  TO_CHAR(q.RUT_EMPRESA, 'FM999G999G999', 'NLS_NUMERIC_CHARACTERS='',.''')
  || '-' || q.DV_EMPRESA                                              AS RUT_EMPRESA,

  UPPER(q.NOMBRE_EMPRESA)                                             AS NOMBRE_EMPRESA,

  ROUND(q.IVA_DECLARADO, 0)                                           AS IVA,

TRUNC(
  MONTHS_BETWEEN(
    (ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), 12) - 1),  
    q.FECHA_INICIO_ACT
  ) / 12
) AS ANIOS_EXISTENCIA,


  TRUNC(q.TOTAL_ASESORIAS_ANIO / 12)                                  AS TOTAL_ASESORIAS_ANUALES,

  TRUNC(
    q.IVA_DECLARADO * (TRUNC(q.TOTAL_ASESORIAS_ANIO / 12) / 100)
  )                                                                   AS DEVOLUCION_IVA,

  CASE
    WHEN TRUNC(q.TOTAL_ASESORIAS_ANIO / 12) > 5 THEN 'CLIENTE PREMIUM'
    WHEN TRUNC(q.TOTAL_ASESORIAS_ANIO / 12) BETWEEN 3 AND 5 THEN 'CLIENTE'
    ELSE 'CLIENTE POCO CONCURRIDO'
  END                                                                 AS TIPO_CLIENTE,

-- PREMIUM => 1 ASESORIA GRATIS, resto => CAPTAR CLIENTE
  CASE
    WHEN TRUNC(q.TOTAL_ASESORIAS_ANIO / 12) > 5 THEN '1 ASESORIA GRATIS'
    ELSE 'CAPTAR CLIENTE'
  END                                                                 AS CORRESPONDE

FROM (
  SELECT
    e.RUT_EMPRESA                    AS RUT_EMPRESA,
    e.DV_EMPRESA                     AS DV_EMPRESA,
    e.NOMEMPRESA                     AS NOMBRE_EMPRESA,
    e.IVA_DECLARADO                  AS IVA_DECLARADO,
    e.FECHA_INICIACION_ACTIVIDADES   AS FECHA_INICIO_ACT,
    COUNT(*)                         AS TOTAL_ASESORIAS_ANIO
  FROM S_EMPRESA e
  JOIN S_ASESORIA a
    ON a.IDEMPRESA = e.IDEMPRESA
  WHERE
    a.FIN >= ADD_MONTHS(TRUNC(SYSDATE, 'YYYY'), -12)
    AND a.FIN <  TRUNC(SYSDATE, 'YYYY')
  GROUP BY
    e.RUT_EMPRESA,
    e.DV_EMPRESA,
    e.NOMEMPRESA,
    e.IVA_DECLARADO,
    e.FECHA_INICIACION_ACTIVIDADES
) q;

COMMIT;

GRANT SELECT ON VW_EMPRESAS_ASESORADAS TO PRY2205_EFT_CON;
COMMIT;

-- INFORME
SELECT *
FROM VW_EMPRESAS_ASESORADAS
ORDER BY NOMBRE_EMPRESA ASC;

-- CASO 3.2
-- CASO 3.2
-- EJECUTAR COMO PRY2205_EFT (OWNER)

-- BORRAR SI EXISTE
BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX IDX_ASESORIA_FIN_EMP';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE INDEX IDX_ASESORIA_FIN_EMP
ON ASESORIA (FIN, IDEMPRESA);

-- ACTUALIZACION DE ESTADISTICAS
BEGIN
  DBMS_STATS.GATHER_TABLE_STATS(USER, 'ASESORIA');
  DBMS_STATS.GATHER_TABLE_STATS(USER, 'EMPRESA');
END;
/

-- VERIFICACION
EXPLAIN PLAN FOR
SELECT * FROM VW_EMPRESAS_ASESORADAS;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

