-- DESDE ADMIN
-- CREACION DE USUARIO 1
CREATE USER PRY2205_USER1
  IDENTIFIED BY "PRY2205.semana_8_1"  
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO PRY2205_USER1;

GRANT CREATE TABLE,
      CREATE VIEW,
      CREATE SYNONYM
TO PRY2205_USER1;

-- NOTA: AQUI SE INSERTARON LAS TABLAS Y DATOS DE ESTAS (USUARIO 1)

-- CREACION DE USUARIO 2
CREATE USER PRY2205_USER2
  IDENTIFIED BY "PRY2205.semana_8_2"                               
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

-- PERMISO DE CONEXION
GRANT CREATE SESSION TO PRY2205_USER2;


GRANT CREATE PUBLIC SYNONYM TO PRY2205_USER1;

-- ROLES
CREATE ROLE PRY2205_ROL_D;
CREATE ROLE PRY2205_ROL_P;

-- ASIGNACION DE ROLES
GRANT PRY2205_ROL_D TO PRY2205_USER1;
GRANT PRY2205_ROL_P TO PRY2205_USER2;


-- PRIVILEGIOS ROL P
GRANT SELECT ON PRY2205_USER1.LIBRO                    TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.EJEMPLAR                 TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.PRESTAMO                 TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.DETALLE_PRESTAMO_MENSUAL TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.EMPLEADO                 TO PRY2205_ROL_P;

-- SINONIMO PUBLICO DESDE USUARIO 1
CREATE PUBLIC SYNONYM SN_EMPLEADO FOR PRY2205_USER1.EMPLEADO;

-- CASO 2
-- COMO ADMIN
GRANT CREATE TABLE,
      CREATE SEQUENCE,
      CREATE TRIGGER
TO PRY2205_USER2;

-- COMO USUARIO 1
-- SINONIMOS PUBLICOS
CREATE PUBLIC SYNONYM SN_LIBRO    FOR PRY2205_USER1.LIBRO;
CREATE PUBLIC SYNONYM SN_EJEMPLAR FOR PRY2205_USER1.EJEMPLAR;
CREATE PUBLIC SYNONYM SN_PRESTAMO FOR PRY2205_USER1.PRESTAMO;
CREATE PUBLIC SYNONYM SN_DETALLE_PM FOR PRY2205_USER1.DETALLE_PRESTAMO_MENSUAL;

-- COMO USUARIO 2
CREATE SEQUENCE SEQ_CONTROL_STOCK
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
CREATE TABLE CONTROL_STOCK_LIBROS (
    ID_CONTROL          NUMBER(6),      
    LIBRO_ID            NUMBER(5),      
    NOMBRE_LIBRO        VARCHAR2(70),   
    TOTAL_EJEMPLARES    NUMBER(5),
    EN_PRESTAMO         NUMBER(5),
    DISPONIBLES         NUMBER(5),
    PORCENTAJE_PRESTAMO NUMBER(5,2),
    STOCK_CRITICO       CHAR(1)
);

INSERT INTO CONTROL_STOCK_LIBROS (
    ID_CONTROL,
    LIBRO_ID,
    NOMBRE_LIBRO,
    TOTAL_EJEMPLARES,
    EN_PRESTAMO,
    DISPONIBLES,
    PORCENTAJE_PRESTAMO,
    STOCK_CRITICO
)
SELECT
    SEQ_CONTROL_STOCK.NEXTVAL                AS ID_CONTROL,      
    l.LIBROID                                AS LIBRO_ID,        
    INITCAP(l.NOMBRE_LIBRO)                  AS NOMBRE_LIBRO,    
    e.total_ejemplares                       AS TOTAL_EJEMPLARES,
    NVL(p.en_prestamo, 0)                    AS EN_PRESTAMO,
    (e.total_ejemplares - NVL(p.en_prestamo, 0)) AS DISPONIBLES,

    ROUND(
        CASE
            WHEN e.total_ejemplares = 0 THEN 0
            ELSE ( NVL(p.en_prestamo, 0) / e.total_ejemplares ) * 100
        END,
        2
    )                                        AS PORCENTAJE_PRESTAMO,

    CASE
        WHEN (e.total_ejemplares - NVL(p.en_prestamo, 0)) > 2 THEN 'S'
        ELSE 'N'
    END                                      AS STOCK_CRITICO
FROM
    SN_LIBRO l

    JOIN (
        SELECT
            ej.LIBROID,
            COUNT(*) AS total_ejemplares
        FROM SN_EJEMPLAR ej
        GROUP BY ej.LIBROID
    ) e
        ON e.LIBROID = l.LIBROID

    JOIN (
        SELECT
            p.LIBROID,
            COUNT(*) AS en_prestamo
        FROM SN_PRESTAMO p
        JOIN SN_EMPLEADO emp
            ON emp.EMPLEADOID = p.EMPLEADOID
        WHERE
            emp.EMPLEADOID IN (150, 180, 190)
            AND EXTRACT(YEAR FROM p.FECHA_INICIO) =
                EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE, -24))
        GROUP BY p.LIBROID
    ) p
        ON p.LIBROID = l.LIBROID;

COMMIT;

-- INFORME
SELECT
    ID_CONTROL,
    LIBRO_ID,
    NOMBRE_LIBRO,
    TOTAL_EJEMPLARES,
    EN_PRESTAMO,
    DISPONIBLES,
    PORCENTAJE_PRESTAMO,
    STOCK_CRITICO
FROM CONTROL_STOCK_LIBROS
ORDER BY LIBRO_ID;

-- CASO 3
-- SINONIMOS PUBLICOS ADICIONALES
CREATE PUBLIC SYNONYM SN_ALUMNO       FOR PRY2205_USER1.ALUMNO;
CREATE PUBLIC SYNONYM SN_CARRERA      FOR PRY2205_USER1.CARRERA;
CREATE PUBLIC SYNONYM SN_REBAJA_MULTA FOR PRY2205_USER1.REBAJA_MULTA;

-- VISTA
--USUARIO 1
CREATE OR REPLACE VIEW VW_DETALLE_MULTAS AS
SELECT
    p.PRESTAMOID                                             AS ID_PRESTAMO,

    INITCAP(
        a.NOMBRE || ' ' || a.APATERNO || ' ' || a.AMATERNO
    )                                                        AS NOMBRE_ALUMNO,

    INITCAP(c.DESCRIPCION)                                   AS NOMBRE_CARRERA,

    l.LIBROID                                                AS ID_LIBRO,
    l.PRECIO                                                 AS VALOR_LIBRO,

    p.FECHA_TERMINO                                          AS FECHA_TERMINO,
    p.FECHA_ENTREGA                                          AS FECHA_ENTREGA,

    TRUNC(p.FECHA_ENTREGA - p.FECHA_TERMINO)                 AS DIAS_ATRASO,

    ROUND(
        TRUNC(p.FECHA_ENTREGA - p.FECHA_TERMINO)
        * (NVL(l.PRECIO, 0) * 0.03),
        0
    )                                                        AS VALOR_MULTA,

    NVL(rm.PORC_REBAJA_MULTA, 0) / 100                       AS PORCENTAJE_REBAJA_MULTA,

    ROUND(
        ROUND(
            TRUNC(p.FECHA_ENTREGA - p.FECHA_TERMINO)
            * (NVL(l.PRECIO, 0) * 0.03),
            0
        )
        * (1 - NVL(rm.PORC_REBAJA_MULTA, 0) / 100),
        0
    )                                                        AS VALOR_REBAJADO
FROM
    SN_PRESTAMO p
    JOIN SN_LIBRO   l  ON l.LIBROID   = p.LIBROID
    JOIN SN_ALUMNO  a  ON a.ALUMNOID  = p.ALUMNOID
    JOIN SN_CARRERA c  ON c.CARRERAID = a.CARRERAID
    LEFT JOIN SN_REBAJA_MULTA rm
           ON rm.CARRERAID = c.CARRERAID
WHERE
    EXTRACT(YEAR FROM p.FECHA_TERMINO) =
        EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE, -24))
    AND p.FECHA_ENTREGA > p.FECHA_TERMINO;


--CONSULTA
SELECT
    ID_PRESTAMO,
    NOMBRE_ALUMNO,
    NOMBRE_CARRERA,
    ID_LIBRO,
    VALOR_LIBRO,
    FECHA_TERMINO,
    FECHA_ENTREGA,
    DIAS_ATRASO,
    VALOR_MULTA,
    PORCENTAJE_REBAJA_MULTA,
    VALOR_REBAJADO
FROM VW_DETALLE_MULTAS
ORDER BY
    FECHA_ENTREGA DESC,
    NOMBRE_ALUMNO ASC;   

-- CASO 3.2
CREATE INDEX IX_PRESTAMO_FECHAS
ON PRESTAMO (FECHA_TERMINO, FECHA_ENTREGA);

----------------
SELECT *
FROM VW_DETALLE_MULTAS
ORDER BY FECHA_ENTREGA DESC;



